[project]
name = "birdjepa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Samuel Stevens", email = "samuel.robert.stevens@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "beartype>=0.22.9",
    "datasets>=4.4.1",
    "huggingface-hub>=1.2.3",
    "hydra-core>=1.3.2",
    "timm>=1.0.22",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "wandb>=0.23.1",
]

[project.scripts]
birdjepa = "birdjepa:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
